server:
  port: ${port:8080}

spring:
  application:
    name: vitcoin

logging:
  file:
    name: ${log.dir:/tmp}/spring-blockchain.main.log

blockchain:
  generationStrategyName:
  nodes:
    - address:
      port:
