name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: 7.4.2
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        if: ${{ github.event_name == 'pull_request' }}
        with:
            paths: ${{ github.workspace }}/blockchain/build/reports/jacoco/test/jacocoTestReport.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            update-comment: true
            title: Code Coverage
            min-coverage-overall: 60
            min-coverage-changed-files: 0
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
            generate-coverage-badge: true
            generate-branches-badge: true
            jacoco-csv-file: blockchain/build/reports/jacoco/test/jacocoTestReport.csv
      - name: Commit and push the badge (if it changed)
        if: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/master'}}
        uses: EndBug/add-and-commit@v7
        with:
            default_author: github_actions
            message: 'Autogenerated JaCoCo coverage badges'
            add: '*.svg'
